RND-313 Add `LoginPage` component along with its dependencies
cloudify-cosmo/cloudify-ui-components pull request #211
Opened 2023-04-21 11:12 UTC by kubama

## Description
Added `LoginPage` component along with its dependencies

## Screenshots / Videos
All components are extracted from stage and preserve their original look'n'feel

## Checklist

- [X] My code follows the [UI Code Style](https://cloudifysource.atlassian.net/l/c/x8fq902p).
- [ ] I followed the [UI Testing Guidelines](https://cloudifysource.atlassian.net/l/cp/udCVfvrx) and verified that all tests/checks have passed.
- [X] I verified if that change requires any update in the [documentation](https://cloudifysource.atlassian.net/l/c/4XKtPocy).
- [X] I added proper labels to this PR.

## Tests
Added stories, snapshots, loki images.
Added unit test for `LoginPage`.

 

## Documentation
Added JSDocs

2023-04-21 14:06 UTC, PatrycjaKubiczek commented
@kubama there is a lot of changes so I won't make it with review today, I'll do it on Monday morning

2023-04-24 14:25 UTC, PatrycjaKubiczek requested changes
Sorry for late review, I was a bit occupied with my own PR ;) 

Looks really good, noticed a couple of minor issues. Besides the things with comments there is one more:
https://github.com/cloudify-cosmo/cloudify-ui-components/blob/ff4aed4f303230d9ec5ed90bda7d3c6893ef6690/src/components/elements/Logo/Logo.tsx#L24 I also notice there is typo in Logo.tsx in `45px x 45x` it should be `45px x 45px`

2023-04-24 14:25 UTC, PatrycjaKubiczek commented on src/components/cloudify/LoginPage/LoginPage.tsx
> +     * Render even handler
```suggestion
     * Render event handler
```

2023-04-24 14:25 UTC, PatrycjaKubiczek commented on src/components/cloudify/LoginPage/LoginPage.tsx
> +     * Wheter to enable first login hint
```suggestion
     * Whether to enable first login hint
```

2023-04-24 14:25 UTC, PatrycjaKubiczek commented on src/components/elements/LogoLabel/LogoLabel.stories.tsx
> +basic.storyName = 'Default';
there is no need to add `basic.storyName = 'Default';` it won't display - I'm currently working on dedicated [ticket ](https://cloudifysource.atlassian.net/browse/RD-6339)to remove this from components repo

2023-04-24 14:25 UTC, PatrycjaKubiczek commented on src/components/layout/LogoPage/LogoPage.stories.tsx
> +basic.storyName = 'Default';
there is no need to add basic.storyName = 'Default'; it won't display - I'm currently working on dedicated [ticket ](https://cloudifysource.atlassian.net/browse/RD-6339)to remove this from components repo

2023-04-24 14:25 UTC, PatrycjaKubiczek commented on src/components/cloudify/LargeProductLogo/LargeProductLogo.stories.tsx
> +basic.storyName = 'Default';
there is no need to add basic.storyName = 'Default'; it won't display - I'm currently working on dedicated [ticket ](https://cloudifysource.atlassian.net/browse/RD-6339)to remove this from components repo

2023-04-24 14:25 UTC, PatrycjaKubiczek commented on src/components/cloudify/LoginPage/LoginPage.stories.tsx
> +basic.storyName = 'Default';
there is no need to add basic.storyName = 'Default'; it won't display - I'm currently working on dedicated [ticket ](https://cloudifysource.atlassian.net/browse/RD-6339)to remove this from components repo

2023-04-24 14:25 UTC, PatrycjaKubiczek commented on src/components/cloudify/LoginPage/LoginPage.tsx
> + * Content of the generic product logic page.
should it be logic or login? 🤔

2023-04-24 14:40 UTC, kubama commented on src/components/elements/LogoLabel/LogoLabel.stories.tsx
> +basic.storyName = 'Default';
Fixed

2023-04-24 14:40 UTC, kubama commented on src/components/cloudify/LargeProductLogo/LargeProductLogo.stories.tsx
> +basic.storyName = 'Default';
Fixed

2023-04-24 14:41 UTC, kubama commented on src/components/cloudify/LoginPage/LoginPage.stories.tsx
> +basic.storyName = 'Default';
Fixed

2023-04-24 14:43 UTC, kubama commented
> I also notice there is typo in Logo.tsx in `45px x 45x` it should be `45px x 45px`

Fixed

2023-04-25 08:09 UTC, kubama commented on src/components/cloudify/LoginPage/LoginPage.tsx
> +                        <Message error style={{ display: 'block', backgroundColor: '#fdeded', boxShadow: 'none' }}>
I searched through the project files and didn't find it defined elsewhere

2023-04-25 08:14 UTC, kubama commented on src/components/cloudify/LoginPage/LoginPage.tsx
> +    loginPageHeaderColor: string;
This component is to be reused in stage as well, so it needs to preserve all props that are needed there

2023-04-25 08:27 UTC, qooban commented on src/components/cloudify/LoginPage/LoginPage.tsx
> +    loginPageHeaderColor: string;
I know. I thought we already use there theme context in Stage for this component, but I see right now we have there `whiteLabel` prop.

In that case let it be like that.

2023-04-25 08:27 UTC, qooban approved these changes

2023-04-25 09:16 UTC, PatrycjaKubiczek approved these changes

2023-04-25 09:40 UTC, merged